swagger: "2.0"
info:
  version: "0.0.1"
  title: Pale Fire Designs
host: localhost:10010 # pointing to local machine for dev purposes
basePath: /
schemes:
  - http # remove this before going to production
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /item:
    x-swagger-router-controller: item
    get:
      operationId: getAll
      description: get all items from Etsy
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetItemsListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: add
      description: add a new item to the website and Etsy
      parameters:
        - name: title
          description: Item properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Item"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /item/{id}:
    x-swagger-router-controller: item
    get:
      operationId: get
      description: get an item
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetItemResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      operationId: update
      description: update an item on the website and Etsy
      parameters:
        - name: id
          description: Item ID
          type: string
          in: path
          required: true
        - name: title
          description: Item properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Item"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      operationId: remove
      description: remove an item from the website and Etsy
      parameters:
        - name: id
          description: Item ID
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  GetItemResponse:
    required:
      - id
    properties:
      id:
        type: string
  Item:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      price:
        type: number
      photos:
        type: array
        items:
          $ref: '#/definitions/Photo'
    required:
      - title
      - description
      - price
      - photos
  Photo:
    type: object
    properties:
      image:
        type: string # change to image
      displayOrder:
        type: number
    required:
      - image
      - displayOrder
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment
    required:
      - success
      - description
  GetItemsListResponse:
    required:
      - items
    properties:
      items:
        type: array
        items: 
          type: object
          properties:
            id:
              type: string
            title:
              type: string
            description:
              type: string
            price:
              type: number
            photos:
              type: array
              items:
                $ref: '#/definitions/Photo'
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
